### PR TITLE
Optional init_strategy and unlimited refinement due to stalled iterations

### PR DESCRIPTION
**Pull request by Tomalwo**
- Made _init_strategy_ optional (default is to execute the strategy). This is necessary for multi-objective RBFOpt (RBFMOpt).
- Added distance check for provided points when _init_strategy_ is skipped.
- Added option _thresh_unlimited_refinement_stalled_ to trigger unlimited refinement based on an impending restart due to stalled iterations. (Possible performance enhancement, but still needs to be benchmarked.)

### CODE REVIEW

**Comment by Tomalwo** [comment]
Hi Giacomo,

The idea is to be able to suppress the initial sampling, and to rely only
on user-provided points instead.
If the sampling is suppressed, there is a check on whether any of the
user-provided points are too close to each other.
This is important for RBFMOpt/MOpossum, which is constantly restarting
RBFOpt with different weights.

Let me know if that helps!
Otherwise, could you perhaps ignore restart(), and merge in the remaining
changes?

Thanks!
Thomas

**Comment by Tomalwo** [comment]
Hi Giacomo,

Here's some more points which you might find useful.

There is an optional Boolean variable *do_init_strategy* in the constructor
of *rbfopt_algorithm* that decides whether the the init strategy should be
executed or not. By default, it is true.
Btw, *do_init_strategy* is not accessible via the command line to prevent
users from using this feature willy-nilly.

In *restart()*, checking whether the current cycle is zero should ensure
that, when a restart happens (as opposed to just starting the algorithm),
the sampling phase happens anyway.

*if(self.current_cycle != 0 or self.do_init_strategy)*

(I just realized that the first condition needs to be added in a couple
more places (everywhere we check whether  self.do_init_strategy is true).)

Thanks!
Thomas

**Comment by gnannicini** [comment]
Have a look at the new branch rc1. I think I implemented all that was included in your PR. I had to change the output log as it cluttered the screen. Can you please test if the new branch does what you need? I can then make a new release after updating the doc.

**Comment by gnannicini** [comment]
Solved in master.

**Pull request closed without merging**
